# Generated by Django 5.2.7 on 2025-10-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(max_length=100, verbose_name="Auteur"),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Poste/Fonction"
                    ),
                ),
                ("image", models.ImageField(upload_to="testimonials/")),
                ("content", models.TextField(verbose_name="Témoignage")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 étoile"),
                            (2, "2 étoiles"),
                            (3, "3 étoiles"),
                            (4, "4 étoiles"),
                            (5, "5 étoiles"),
                        ],
                        default=5,
                    ),
                ),
            ],
        ),
    ]
