# Generated by Django 5.2.7 on 2025-10-24 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0005_feedbackuser_remove_student_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testimonial",
            name="image",
        ),
        migrations.RemoveField(
            model_name="testimonial",
            name="position",
        ),
    ]
